### ISSUE TITLE
`getSize` option for LRU

### ISSUE THREAD

**Issue by eschwartz** [four43/node-crisp-cache#11]
It would be nice if there was a `getSize` option for the LRU cache. This would let me limit the actual size of my cache in memory, instead of just the number of object (which could all be different sizes).

For example:

```js
var cache = new CrispCache({
   maxSize: 100,
   getSize: buffer => buffer.size
});

cache.set(new Buffer(90));   // room for this guy
cache.set(new Buffer(9));     // room for this guy
cache.set(new Buffer(2));     // no more room for this guy -- we're gonna have to boot someone
```

**Comment by four43** [comment]
This is already a thing, but it sounds like it wasn't clear in the docs. I'll add better explanation of these features.

**Comment by eschwartz** [comment]
One advantage of accepting a `getSize` option is that it would separate the cache initialization options from the `fetcher` logic. Consider a case where you are wrapping an existing library:

```js
// In some third-party or otherwise far-away code
var awesomeIo = function(cb) {
  /// do awesome IO stuff
  cb(null, result);
}

// In my implementation code, I want to wrap awesomeIo in a cache
var awesomeIoCache = CrispCache({
  fetcher: require('awesome-io'),
  maxSize: 100
})
```

This will fail, because awesome-io doesn't send back a cache item size. I could wrap the fetcher, as a workaround.

Alternatively:

```js
var awesomeIoCache = CrispCache({
  fetcher: require('awesome-io'),
  maxSize: 100,
  getSize: res => res.howBigAmI
})
```
